name: startup help
favicon: null
layout_spectrum: 0.7966853131074458
typography_spectrum: 0.7791417492553592
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.24686595308594406
  lightness: 0.029531912645325065
  saturation: 0.592996823368594
  rhythmicContrast: 0.660790951224044
purpose: []
